### ISSUE TITLE
[BUG] v0.9.0(v0.9.1) on minecraft 1.19 not starting

### ISSUE THREAD

**Issue by Whitebrim** [CraftoryStudios/Craftory-Tech#225]
**Description**
Trying new build on 1.19 server

This build → https://github.com/CraftoryStudios/Craftory-Tech/releases/tag/v0.9.1

**Screenshots / Video**
![image](https://user-images.githubusercontent.com/23287829/180746911-79d164f9-64fb-4a18-a6fc-8828fee4d4eb.png)

**Server Log**
```
[12:27:05 INFO]: [Craftory] Enabling Craftory v0.9.0
[12:27:05 ERROR]: Error occurred while enabling Craftory v0.9.0 (Is it up to date?)
java.lang.NoSuchMethodError: 'io.sentry.context.Context io.sentry.Sentry.getContext()'
	at tech.brettsaunders.craftory.Utilities.createConfigs(Utilities.java:178) ~[Craftory-0.9.0.jar:?]
	at tech.brettsaunders.craftory.Craftory.onEnable(Craftory.java:106) ~[Craftory-0.9.0.jar:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[pufferfish-api-1.19-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370) ~[pufferfish-api-1.19-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:541) ~[pufferfish-api-1.19-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.v1_19_R1.CraftServer.enablePlugin(CraftServer.java:563) ~[pufferfish-1.19.jar:git-Pufferfish-20]
	at org.bukkit.craftbukkit.v1_19_R1.CraftServer.enablePlugins(CraftServer.java:477) ~[pufferfish-1.19.jar:git-Pufferfish-20]
	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:281) ~[pufferfish-1.19.jar:git-Pufferfish-20]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1123) ~[pufferfish-1.19.jar:git-Pufferfish-20]
	at net.minecraft.server.MinecraftServer.lambda$spin$1(MinecraftServer.java:304) ~[pufferfish-1.19.jar:git-Pufferfish-20]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
[12:27:05 INFO]: [Craftory] Disabling Craftory v0.9.0
```

**Version Infomation**
Pufferfish 1.19 minecraft server (build 20)

**Comment by brettsaunders21** [comment]
In the plugin config set error report enabled to false

**Comment by Whitebrim** [comment]
This worked
